name: Ruby Gem

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Release Gem
      if: contains(github.ref, 'refs/tags/v')
      uses: cadwallion/publish-rubygems-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        RELEASE_COMMAND: rake release
